using System;
using UnityEngine;

public class Cooldown_Example : MonoBehaviour
{
   private SpriteRenderer sr;

   [SerializeField] private float redColorDuration = 1;

   public float currentTimeInGame;
   public float lastTimeWasDamaged;
   private void Awake()
   {
      sr = GetComponent<SpriteRenderer>();
   }

   private void Update()
   {
      ChanceColorIfNeeded();
   }

   private void ChanceColorIfNeeded()
   {
      currentTimeInGame = Time.time;

      if (currentTimeInGame > lastTimeWasDamaged + redColorDuration)
      {
         if(sr.color != Color.white)
            sr.color = Color.white;
      }
   }

   public void TakeDamage()
   {
      sr.color = Color.red;
      lastTimeWasDamaged = Time.time;

   }

   private void TurnWhite()
   {
      sr.color = Color.white;
   }
}
